ALTER TABLE IF EXISTS gitrepo ADD COLUMN IF NOT EXISTS service VARCHAR(255);
ALTER TABLE IF EXISTS gitrepo ADD COLUMN IF NOT EXISTS auth_type VARCHAR(255);
ALTER TABLE IF EXISTS gitrepo ADD COLUMN IF NOT EXISTS login VARCHAR(255);
ALTER TABLE IF EXISTS gitrepo ADD COLUMN IF NOT EXISTS password VARCHAR(255);
ALTER TABLE IF EXISTS gitrepo ADD COLUMN IF NOT EXISTS status VARCHAR(255) DEFAULT 'OK';

UPDATE gitrepo
SET
    service = 'axenapi-md-files',
    auth_type = 'TOKEN'
WHERE url = 'http://gitlab/'
